### ISSUE TITLE
Improve README (Run the app, convert screenshot to gif)

### ISSUE THREAD

**Issue by Aneesh540** [Aneesh540/VSE#2]
Currently README contains 3 screenshot of app. Convert these images into GIF format to reduce readme length
Further improvement is to Run the app and make a video of it then convert it into GIF format to update readme

**Comment by ravigautamcs** [comment]
I can do this

**Comment by ravigautamcs** [comment]
Can you tell me how to upload the gif file in github code.
I am currently doing all the from my smartphone. Pls tell me I want to learn

**Comment by Aneesh540** [comment]
Yes sure. 
One short way is to download 3 images, convert images -> GIF & update README file by removing images and adding GIF instead.
Then send PR
(Since images in GIF can change quickly, take multiple copy of a single image so that one image can be seen for atleast 0.5-1 seconds)
conversion example (image1 + image1 + image2 + image2 + image3 + image3) -----> (convert into GIF)

**Comment by ravigautamcs** [comment]
Thankyou

**Comment by ravigautamcs** [comment]
This is resolved. By me

**Comment by ravigautamcs** [comment]
Could you please help me. How can i improve.
